name: auto_app
description: A Flutter application for searching cars from auto.ru.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^2.17.1

dependencies:
  flutter:
    sdk: flutter

  core:
    path: core
  
  core_ui:
    path: core_ui

  data:
    path: data

  domain:
    path: domain

  equatable: ^2.0.3
  get_it: ^7.2.0
  flutter_bloc: ^8.0.1
  bloc: ^8.0.3
  cupertino_icons: ^1.0.5
  favorite_button: ^0.0.4
  persistent_bottom_nav_bar_v2: ^4.2.4
  http: ^0.13.5
  carousel_slider: ^4.1.1
  shared_preferences: ^2.0.15
  sqflite: ^2.0.3
  path_provider: ^2.0.11
  flutter_form_builder: ^7.5.0
  flutter_local_notifications: ^9.7.0
  timezone: ^0.8.0
  flutter_native_timezone: ^2.0.0
  provider: ^6.0.3
  url_launcher: ^6.1.5
  flutter_email_sender: ^5.1.0
  photo_view: ^0.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.9.3

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/icons/app_icon.png"
  image_path_ios: "assets/icons/app_icon.png"


flutter:

  uses-material-design: true

  assets:
    - assets/images/car_logo.png
    - assets/images/car_logo_new.png

  fonts:
    - family: SF UI Display
      fonts:
        - asset: assets/fonts/sf-ui/SFUIDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/sf-ui/SFUIDisplay-Semibold.ttf
          weight: 600
        - asset: assets/fonts/sf-ui/SFUIDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/sf-ui/SFUIDisplay-Regular.ttf
          weight: 400
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
          weight: 500
