name: auto_app
description: A Flutter application for searching cars from auto.ru.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.4
  favorite_button: ^0.0.4
  persistent_bottom_nav_bar: any
  http: ^0.13.4
  carousel_slider: ^4.0.0
  shared_preferences: ^2.0.13
  sqflite: ^2.0.2
  path_provider: ^2.0.9
  flutter_form_builder: ^7.1.1
  flutter_local_notifications: ^9.4.0
  timezone: ^0.8.0
  flutter_native_timezone: ^2.0.0
  provider: ^6.0.2
  url_launcher: ^6.0.20
  flutter_email_sender: ^5.1.0
  photo_view: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/car_logo.png
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #